name: react-native-android-build-apk
on:
  push:
    branches:
      - master
#on:
#  # Trigger the workflow when repository_dispatch is invoked via lambda
#  repository_dispatch:
#   types: workflow-trigger
#   branches:
#     - master
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
#      - uses: actions/checkout@v2
#      - name: Install npm dependencies
#        run: |
#          npm install
#      - name: Build Android Release
#        run: |
#          cd android && ./gradlew assembleRelease
#      - name: Create Artifact
#        uses: actions/upload-artifact@v1
#        with:
#          name: app-release.apk
#          path: android/app/build/outputs/apk/release/
      - name: ls -l
        id: list files
        run: |
          ls -l
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'app.js'      # optional: defaults to entire repository