name: react-native-android-build-apk
on:
  push:
    branches:
      - master
#on:
#  # Trigger the workflow when repository_dispatch is invoked via lambda
#  repository_dispatch:
#   types: workflow-trigger
#   branches:
#     - master
jobs:
#  install-and-test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install npm
#        run: |
#          npm install
  build-android:
#    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm
        run: |
          npm install
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Create Artifact
        uses: actions/upload-artifact@v1
        with:
          name: native-app-${RANDOM}.apk
          path: android/app/build/outputs/apk/release/
      - name: Deploy to S3
      # All commands after this point have access to the AWS CLI
        run: |
          aws s3 cp android/app/build/outputs/apk/release/ s3://tamuz-mobile-artifacts/ --recursive --exclude "*" --include "*.apk" --acl public-read-write